// /**
//  * This code was generated by v0 by Vercel.
//  * @see https://v0.dev/t/7NCuiO9V3pt
//  * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
//  */

// /** Add fonts into your Next.js project:

// import { Inter } from 'next/font/google'

// inter({
//   subsets: ['latin'],
//   display: 'swap',
// })

// To read more about using these font, please visit the Next.js documentation:
// - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
// - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
// **/
// import {
//   Card,
//   CardHeader,
//   CardContent,
//   CardFooter,
// } from "@/components/ui/card";
// import { useSelector } from "react-redux";
// import { Link } from "react-router-dom";

// export const DailyTaskComp = () => {
//   const { tasks, user } = useSelector((state) => state.user);
//   console.log("Member tasks :", tasks);
//   function formatDate(dateString) {
//     const date = new Date(dateString);
//     const options = { year: "numeric", month: "long", day: "numeric" };
//     return date.toLocaleDateString("en-US", options);
//   }

//   return (
//     // <Card className="bg-[#000000] rounded-xl">
//       <Card className="h-auto bg-blue-400 border border-blue-600 rounded-lg shadow-sm text-card-foreground transform transition-transform duration-300 ease-in-out hover:-translate-y-0.5 hover:scale-[1.02] hover:shadow-md">
//       {tasks &&
//         tasks.length > 0 ?
//         tasks.map((task) => (
//           <>
//             {" "}
//             <CardHeader className="bg-[#000000] rounded-t-xl px-6 py-4">
//               <h3 className="text-xl font-bold text-white font-['Poppins', 'sans-serif']">
//                 Daily Tasks
//               </h3>
//             </CardHeader>
//             <CardContent className="px-6 py-4">
//               <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
//                 <div>
//                   <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                     Date
//                   </h3>
//                   <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//                     <li className="flex items-center gap-2">
//                        <span> {formatDate(task.date)}</span>
//                     </li>
//                   </ul>
//                 </div>
//                 <div>
//                   <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                     Plan Name
//                   </h3>
//                   <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//                     <li className="flex items-center gap-2">
//                        <span> {user.planName}</span>
//                     </li>
//                   </ul>
//                 </div>
//                 <div>
//                   <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                     Member Status
//                   </h3>
//                   <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//                     <li className="flex items-center gap-2">
//                        <div className="rounded-full bg-[#1f2937] px-2 py-1 text-sm font-medium text-white">
//                         {task.memberStatus}
//                       </div>
//                     </li>
//                   </ul>
//                 </div>
//                 <div>
//                   <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                     Created Date
//                   </h3>
//                   <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//                     <li className="flex items-center gap-2">
//                        <span>{formatDate(task.createdAt)}</span>
//                     </li>
//                   </ul>
//                 </div>
//                 <div>
//                   <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                     Warm Up Exercises
//                   </h3>

//                   <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//                     {task.warmupExercises.map((we) => (
//                       <li
//                         key={we._id}
//                         className="flex flex-row items-center gap-1"
//                       >
//                         <div className="flex items-center gap-2">
//                            <span>{we.name}</span>
//                         </div>
//                         <div className="ml-4 text-xs">
//                           <span>Reps: {we.reps}</span> |{" "}
//                           <span>Sets: {we.sets}</span>
//                         </div>
//                       </li>
//                     ))}
//                   </ul>
//                 </div>
//                 <div>
//                   <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                     Main Exercises
//                   </h3>
//                   <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//                     {task.mainExercises.map((we) => (
//                       <li
//                         key={we._id}
//                         className="flex flex-row items-center gap-1"
//                       >
//                         <div className="flex items-center gap-2">
//                            <span>{we.name}</span>
//                         </div>
//                         <div className="ml-4 text-xs">
//                           <span>Reps: {we.reps}</span> |{" "}
//                           <span>Sets: {we.sets}</span>
//                         </div>
//                       </li>
//                     ))}
//                   </ul>
//                 </div>
//                 <div>
//                   <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                     Cool Down Exercises
//                   </h3>
//                   <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//                     {task.cooldownExercises.map((we) => (
//                       <li
//                         key={we._id}
//                         className="flex flex-row items-center gap-1"
//                       >
//                         <div className="flex items-center gap-2">
//                            <span>{we.name}</span>
//                         </div>
//                         <div className="ml-4 text-xs">
//                           <span>Reps: {we.reps}</span> |{" "}
//                           <span>Sets: {we.sets}</span>
//                         </div>
//                       </li>
//                     ))}
//                   </ul>
//                 </div>
//                 <Card className="bg-[#000000] p-3 rounded-xl">
//                   <div>
//                     <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                       Post-Workout Advice
//                     </h3>{" "}
//                     <p>{task.preWorkoutAdvice}</p>
//                   </div>
//                 </Card>
//                 <Card className="bg-[#000000] p-3 rounded-xl">
//                   <div>
//                     <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                       Post-Workout Advice
//                     </h3>{" "}
//                     <p>{task.postWorkoutAdvice}</p>
//                   </div>
//                 </Card>
//                 <Card className="bg-[#000000] p-3 rounded-xl">
//                   <div>
//                     <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                       Post-Workout Advice
//                     </h3>{" "}
//                     <p>{task.dailyHydration}</p>
//                   </div>
//                 </Card>
//                 <Card className="bg-[#000000] p-3 rounded-xl">
//                   <div>
//                     <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                       Post-Workout Advice
//                     </h3>{" "}
//                     <p>{task.balancedDietAdvice}</p>
//                   </div>
//                 </Card>
//               </div>
//             </CardContent>
//           </>
//         )):
        
//       (
//         <div className="p-2">No Tasks</div>
//       )}
//     </Card>
//   );
// };

// export default DailyTaskComp;
// --------------------- new  :
// /**
//  * This code was generated by v0 by Vercel.
//  * @see https://v0.dev/t/7NCuiO9V3pt
//  * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
//  */

// /** Add fonts into your Next.js project:

// import { Inter } from 'next/font/google'

// inter({
//   subsets: ['latin'],
//   display: 'swap',
// })

// To read more about using these font, please visit the Next.js documentation:
// - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
// - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
// **/
// import {
//   Card,
//   CardHeader,
//   CardContent,
//   CardFooter,
// } from "@/components/ui/card";
// import { useSelector } from "react-redux";
// import { Link } from "react-router-dom";

// export const DailyTaskComp = () => {
//   const { tasks, user } = useSelector((state) => state.user);
//   console.log("Member tasks :", tasks);
//   function formatDate(dateString) {
//     const date = new Date(dateString);
//     const options = { year: "numeric", month: "long", day: "numeric" };
//     return date.toLocaleDateString("en-US", options);
//   }

//   return (
//     // <Card className="bg-[#000000] rounded-xl">
//       <Card className="h-auto bg-blue-400 border border-blue-600 rounded-lg shadow-sm text-card-foreground transform transition-transform duration-300 ease-in-out hover:-translate-y-0.5 hover:scale-[1.02] hover:shadow-md">
//       {tasks &&
//         tasks.length > 0 ?
//         tasks.map((task) => (
//           <>
//             {" "}
//             <CardHeader className="bg-[#000000] rounded-t-xl px-6 py-4">
//               <h3 className="text-xl font-bold text-white font-['Poppins', 'sans-serif']">
//                 Daily Tasks
//               </h3>
//             </CardHeader>
//             <CardContent className="px-6 py-4">
//               <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
//                 <div>
//                   <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                     Date
//                   </h3>
//                   <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//                     <li className="flex items-center gap-2">
//                        <span> {formatDate(task.date)}</span>
//                     </li>
//                   </ul>
//                 </div>
//                 <div>
//                   <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                     Plan Name
//                   </h3>
//                   <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//                     <li className="flex items-center gap-2">
//                        <span> {user.planName}</span>
//                     </li>
//                   </ul>
//                 </div>
//                 <div>
//                   <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                     Member Status
//                   </h3>
//                   <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//                     <li className="flex items-center gap-2">
//                        <div className="rounded-full bg-[#1f2937] px-2 py-1 text-sm font-medium text-white">
//                         {task.memberStatus}
//                       </div>
//                     </li>
//                   </ul>
//                 </div>
//                 <div>
//                   <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                     Created Date
//                   </h3>
//                   <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//                     <li className="flex items-center gap-2">
//                        <span>{formatDate(task.createdAt)}</span>
//                     </li>
//                   </ul>
//                 </div>
//                 <div>
//                   <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                     Warm Up Exercises
//                   </h3>

//                   <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//                     {task.warmupExercises.map((we) => (
//                       <li
//                         key={we._id}
//                         className="flex flex-row items-center gap-1"
//                       >
//                         <div className="flex items-center gap-2">
//                            <span>{we.name}</span>
//                         </div>
//                         <div className="ml-4 text-xs">
//                           <span>Reps: {we.reps}</span> |{" "}
//                           <span>Sets: {we.sets}</span>
//                         </div>
//                       </li>
//                     ))}
//                   </ul>
//                 </div>
//                 <div>
//                   <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                     Main Exercises
//                   </h3>
//                   <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//                     {task.mainExercises.map((we) => (
//                       <li
//                         key={we._id}
//                         className="flex flex-row items-center gap-1"
//                       >
//                         <div className="flex items-center gap-2">
//                            <span>{we.name}</span>
//                         </div>
//                         <div className="ml-4 text-xs">
//                           <span>Reps: {we.reps}</span> |{" "}
//                           <span>Sets: {we.sets}</span>
//                         </div>
//                       </li>
//                     ))}
//                   </ul>
//                 </div>
//                 <div>
//                   <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                     Cool Down Exercises
//                   </h3>
//                   <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//                     {task.cooldownExercises.map((we) => (
//                       <li
//                         key={we._id}
//                         className="flex flex-row items-center gap-1"
//                       >
//                         <div className="flex items-center gap-2">
//                            <span>{we.name}</span>
//                         </div>
//                         <div className="ml-4 text-xs">
//                           <span>Reps: {we.reps}</span> |{" "}
//                           <span>Sets: {we.sets}</span>
//                         </div>
//                       </li>
//                     ))}
//                   </ul>
//                 </div>
//                 <Card className="bg-[#000000] p-3 rounded-xl">
//                   <div>
//                     <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                       Post-Workout Advice
//                     </h3>{" "}
//                     <p>{task.preWorkoutAdvice}</p>
//                   </div>
//                 </Card>
//                 <Card className="bg-[#000000] p-3 rounded-xl">
//                   <div>
//                     <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                       Post-Workout Advice
//                     </h3>{" "}
//                     <p>{task.postWorkoutAdvice}</p>
//                   </div>
//                 </Card>
//                 <Card className="bg-[#000000] p-3 rounded-xl">
//                   <div>
//                     <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                       Post-Workout Advice
//                     </h3>{" "}
//                     <p>{task.dailyHydration}</p>
//                   </div>
//                 </Card>
//                 <Card className="bg-[#000000] p-3 rounded-xl">
//                   <div>
//                     <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
//                       Post-Workout Advice
//                     </h3>{" "}
//                     <p>{task.balancedDietAdvice}</p>
//                   </div>
//                 </Card>
//               </div>
//             </CardContent>
//           </>
//         )):
        
//       (
//         <div className="p-2">No Tasks</div>
//       )}
//     </Card>
//   );
// };

// export default DailyTaskComp;






// import {
//   Card,
//   CardHeader,
//   CardContent,
//   CardFooter,
// } from "@/components/ui/card";
// import { useSelector } from "react-redux";

// export const DailyTaskComp = () => {
//   const { tasks, user } = useSelector((state) => state.user);
//   console.log("Member tasks :", tasks);

//   function formatDate(dateString) {
//     const date = new Date(dateString);
//     const options = { year: "numeric", month: "long", day: "numeric" };
//     return date.toLocaleDateString("en-US", options);
//   }

//   return (
//     <div className="space-y-6">
//       {tasks && tasks.length > 0 ? (
//         tasks.map((task, index) => (
//           <Card
//             key={index}
//             className="h-auto bg-blue-400 border border-blue-600 rounded-lg shadow-md space-y-4 p-4"
//           >
//             <DailyTaskHeader />
//             <CardContent className="px-6 py-4 space-y-4">
//               <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
//                 <TaskDate date={task.date} formatDate={formatDate} />
//                 <PlanName planName={user.planName} />
//                 <MemberStatus status={task.memberStatus} />
//                 <CreatedDate createdAt={task.createdAt} formatDate={formatDate} />
//               </div>
//               <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
//                 <ExercisesSection title="Warm Up Exercises" exercises={task.warmupExercises} />
//                 <ExercisesSection title="Main Exercises" exercises={task.mainExercises} />
//                 <ExercisesSection title="Cool Down Exercises" exercises={task.cooldownExercises} />
//               </div>
//               <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
//                 <AdviceCard title="Post-Workout Advice" advice={task.preWorkoutAdvice} />
//                 <AdviceCard title="Post-Workout Advice" advice={task.postWorkoutAdvice} />
//                 <AdviceCard title="Daily Hydration" advice={task.dailyHydration} />
//                 <AdviceCard title="Balanced Diet Advice" advice={task.balancedDietAdvice} />
//               </div>
//             </CardContent>
//           </Card>
//         ))
//       ) : (
//         <div className="p-2">No Tasks</div>
//       )}
//     </div>
//   );
// };

// const DailyTaskHeader = () => (
//   <CardHeader className="bg-[#000000] rounded-t-xl px-6 py-4">
//     <h3 className="text-xl font-bold text-white font-['Poppins', 'sans-serif']">
//       Daily Tasks
//     </h3>
//   </CardHeader>
// );

// const TaskDate = ({ date, formatDate }) => (
//   <div>
//     <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">Date</h3>
//     <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//       <li className="flex items-center gap-2">
//         <span>{formatDate(date)}</span>
//       </li>
//     </ul>
//   </div>
// );

// const PlanName = ({ planName }) => (
//   <div>
//     <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">Plan Name</h3>
//     <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//       <li className="flex items-center gap-2">
//         <span>{planName}</span>
//       </li>
//     </ul>
//   </div>
// );

// const MemberStatus = ({ status }) => (
//   <div>
//     <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">Member Status</h3>
//     <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//       <li className="flex items-center gap-2">
//         <div className="rounded-full bg-[#1f2937] px-2 py-1 text-sm font-medium text-white">
//           {status}
//         </div>
//       </li>
//     </ul>
//   </div>
// );

// const CreatedDate = ({ createdAt, formatDate }) => (
//   <div>
//     <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">Created Date</h3>
//     <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//       <li className="flex items-center gap-2">
//         <span>{formatDate(createdAt)}</span>
//       </li>
//     </ul>
//   </div>
// );

// const ExercisesSection = ({ title, exercises }) => (
//   <div>
//     <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">{title}</h3>
//     <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
//       {exercises.map((we) => (
//         <li key={we._id} className="flex flex-row items-center gap-1">
//           <div className="flex items-center gap-2">
//             <span>{we.name}</span>
//           </div>
//           <div className="ml-4 text-xs">
//             <span>Reps: {we.reps}</span> | <span>Sets: {we.sets}</span>
//           </div>
//         </li>
//       ))}
//     </ul>
//   </div>
// );

// const AdviceCard = ({ title, advice }) => (
//   <Card className="bg-[#000000] p-3 rounded-xl border border-blue-500">
//     <div>
//       <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">{title}</h3>
//       <p className="text-white">{advice}</p>
//     </div>
//   </Card>
// );

// export default DailyTaskComp;


import {
  Card,
  CardHeader,
  CardContent,
  CardFooter,
} from "@/components/ui/card";
import { useSelector } from "react-redux";

export const DailyTaskComp = () => {
  const { tasks, user } = useSelector((state) => state.user);
  console.log("Member tasks :", tasks);

  function formatDate(dateString) {
    const date = new Date(dateString);
    const options = { year: "numeric", month: "long", day: "numeric" };
    return date.toLocaleDateString("en-US", options);
  }

  return (
    <div className="space-y-6 overflow-hidden">
      {tasks && tasks.length > 0 ? (
        tasks.map((task, index) => (
          <Card
            key={index}
            className="h-auto bg-blue-400 border border-blue-600 rounded-lg shadow-md space-y-4 p-4"
          >
            <DailyTaskHeader />
            <CardContent className="px-6 py-4 space-y-4">
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <TaskDate date={task.date} formatDate={formatDate} />
                <PlanName planName={user.planName} />
                <MemberStatus status={task.memberStatus} />
                <CreatedDate createdAt={task.createdAt} formatDate={formatDate} />
              </div>
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <ExercisesSection title="Warm Up Exercises" exercises={task.warmupExercises} />
                <ExercisesSection title="Main Exercises" exercises={task.mainExercises} />
                <ExercisesSection title="Cool Down Exercises" exercises={task.cooldownExercises} />
              </div>
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <AdviceCard title="Pre-Workout Advice" advice={task.preWorkoutAdvice} />
                <AdviceCard title="Post-Workout Advice" advice={task.postWorkoutAdvice} />
                <AdviceCard title="Daily Hydration" advice={task.dailyHydration} />
                <AdviceCard title="Balanced Diet Advice" advice={task.balancedDietAdvice} />
              </div>
            </CardContent>
          </Card>
        ))
      ) : (
        <div className="p-2">No Tasks</div>
      )}
    </div>
  );
};

const DailyTaskHeader = () => (
  <CardHeader className="bg-[#000000] rounded-t-xl px-6 py-4">
    <h3 className="text-xl font-bold text-white font-['Poppins', 'sans-serif']">
      Daily Tasks
    </h3>
  </CardHeader>
);

const TaskDate = ({ date, formatDate }) => (
  <div>
    <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">Date</h3>
    <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
      <li className="flex items-center gap-2">
        <span>{formatDate(date)}</span>
      </li>
    </ul>
  </div>
);

const PlanName = ({ planName }) => (
  <div>
    <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">Plan Name</h3>
    <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
      <li className="flex items-center gap-2">
        <span>{planName}</span>
      </li>
    </ul>
  </div>
);

const MemberStatus = ({ status }) => (
  <div>
    <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">Member Status</h3>
    <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
      <li className="flex items-center gap-2">
        <div className="rounded-full bg-[#1f2937] px-2 py-1 text-sm font-medium text-white">
          {status}
        </div>
      </li>
    </ul>
  </div>
);

const CreatedDate = ({ createdAt, formatDate }) => (
  <div>
    <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">Created Date</h3>
    <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
      <li className="flex items-center gap-2">
        <span>{formatDate(createdAt)}</span>
      </li>
    </ul>
  </div>
);

const ExercisesSection = ({ title, exercises }) => (
  <div>
    <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">{title}</h3>
    <ul className="mt-2 space-y-2 text-white font-['Poppins', 'sans-serif'] text-sm">
      {exercises.map((we) => (
        <li key={we._id} className="flex flex-row items-center gap-1">
          <div className="flex items-center gap-2">
            <span>{we.name}</span>
          </div>
          <div className="ml-4 text-xs">
            <span>Reps: {we.reps}</span> | <span>Sets: {we.sets}</span>
          </div>
        </li>
      ))}
    </ul>
  </div>
);

const AdviceCard = ({ title, advice }) => (
  <Card
    className="bg-[#000000] p-3 rounded-xl border border-blue-500 relative transition-transform duration-300 ease-in-out transform hover:scale-105 hover:shadow-lg"
    style={{ zIndex: 10 }} // Ensures it's on top during hover without affecting layout
  >
    <div className="p-4">
      <h3 className="text-lg font-bold text-white font-['Poppins', 'sans-serif']">
        {title}
      </h3>
      <p className="text-white">{advice}</p>
    </div>
  </Card>
);

export default DailyTaskComp;
