/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CBE1kAJ2QUz
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { Arimo } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import TrainerSidePanel from "@/Component/TrainerSidePanel";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
} from "@/components/ui/card";
import { fetchUsersDetails } from "@/redux/trainerSlice";
import { UsersIcon } from "lucide-react";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useParams } from "react-router-dom";

export function PlanDetailsComp() {
  const { id } = useParams();
  const { plans, planUserDetails } = useSelector((state) => state.trainer);
  const dispatch = useDispatch();
  const planInfo = plans.find((plan) => plan._id === id);
  console.log("plan info :", planInfo.users);
  useEffect(() => {
    dispatch(fetchUsersDetails(planInfo.users));
  }, [dispatch, planInfo]);

  console.log("planUsersDetails :", planUserDetails);
  function convertDateTime(isoDateTime) {
    // Parse the input ISO 8601 date-time string
    const date = new Date(isoDateTime);

    // Define the desired format options
    const options = {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "numeric",
      minute: "numeric",
      hour12: true,
    };

    // Convert to the desired format
    return date.toLocaleDateString("en-US", options);
  }

  return (
    <TrainerSidePanel>
      {" "}
      <div className="dark:bg-black bg-black text-white transition-colors duration-500 flex items-center justify-center ">
        <Card className="w-full max-w-3xl animate-fade-in border-opacity-20">
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle className="mb-2">{planInfo.name}</CardTitle>
                <CardDescription>{planInfo.description}</CardDescription>
              </div>
              <div className="flex items-center space-x-4">
                <div className="flex items-center space-x-1">
                  <DollarSignIcon className="h-5 w-5 text-primary" />
                  <span className="text-primary font-medium">
                    {planInfo.price}
                  </span>
                </div>
                <div className="flex items-center space-x-1">
                  <CalendarIcon className="h-5 w-5 text-muted-foreground" />
                  <span className="text-muted-foreground">
                    {planInfo.duration}
                  </span>
                </div>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <div className="space-y-4 animate-fade-in">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <UserIcon className="h-5 w-5 text-muted-foreground" />
                  <span className="text-muted-foreground">
                    {planInfo.users.length} Users
                  </span>
                </div>
                <div className="flex items-center space-x-2">
                  {planInfo.status === "active" && (
                    <CircleCheckIcon className="h-5 w-5 text-green-500" />
                  )}

                  <span className="text-green-500 font-medium">
                    {planInfo.status}
                  </span>
                </div>
              </div>

              <div className="flex items-center  space-x-2">
                <CalendarIcon className="h-5 w-5 text-muted-foreground" />
                <span className="text-muted-foreground">
                  Created at {convertDateTime(planInfo.createdAt)}
                </span>
              </div>
              <div className="flex  items-center space-x-2">
                <UsersIcon className="h-5 w-5 text-muted-foreground mt-5" />
                <span className="text-muted-foreground mt-5">
                  list of users
                </span>
              </div>
              {planUserDetails.map((plan) => (
                <>
                  <div className="flex items-center space-x-2">
                    <UserIcon className="h-5 w-5 text-muted-foreground" />
                    <div className="flex gap-3">
                      <div className="text-muted-foreground">{plan.name}</div>
                      <div className="text-muted-foreground">{plan.email}</div>
                    </div>
                  </div>
                </>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </TrainerSidePanel>
  );
}

function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  );
}

function CircleCheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  );
}

function DollarSignIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="2" y2="22" />
      <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
    </svg>
  );
}

function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}
